test_route:
  path: /add/{a}/{b}
  methods: [GET]
  controller: controller.T:Add

test_route_post:
  path: /add
  methods: [POST]
  controller: controller.T:AddPost

test_soap_route:
  path: /
  methods: [POST]
  headers:
    SOAPAction: getVersionInformation
  controller: controller.T:GetVersion
